### ISSUE TITLE
New Logo/Icon Proposal

### ISSUE THREAD

**Issue by mansya** [Souravgoswami/Space-Clock#1]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by mansya** [comment]
hi sir. how about this offer? are you interested ?

**Comment by Souravgoswami** [comment]
Wow! That will be amazing!
Sorry for very very late reply!!
I have actually added a logo. But I would like you to submit a logo!
The logo has to be a 32x32..64x64 image.

Thank you very much.

**Comment by mansya** [comment]
I have designed the logo for this project. What do you think ? do you like it ? if yes let me know and if there are changes please let me know.
![Space Clock](https://user-images.githubusercontent.com/33461607/57753227-c3880280-7715-11e9-820f-c738ffdbbe8b.png)

**Comment by Souravgoswami** [comment]
Sure, it's a very creative logo! I love the 2nd one!

**Comment by mansya** [comment]
it was incredible. however I am making changes to this form. do you like it ? if yes. which one you like.
![Space Clock rocket](https://user-images.githubusercontent.com/33461607/57937183-9bec9200-78ef-11e9-82d3-aff1eea9d945.png)

**Comment by Souravgoswami** [comment]
It's a very creative design. I am confused! How about the 2nd one?

**Comment by mansya** [comment]
I am also interested in the second. I will work on the design for number 2. please wait. I will finish this as soon as possible

**Comment by Souravgoswami** [comment]
Thank you very much. Also, take some time.
You can also email me when it's done souravgoswami@protonmail.com

**Comment by mansya** [comment]
hi. I have finished all the files for this new logo design. please check [**PULL REQUESTS**](https://github.com/Souravgoswami/Space-Clock/pull/2). and I also gave all the files on this [Drive](https://drive.google.com/open?id=1qcQZEXgWMDpYXHqECygaoPGgvjRULuEi)
